title: Ocean Mallik Talks
description: Notes, tutorials, and experiments by Ocean Mallik.
url: "https://blog.oceanmallik.com"
baseurl: ""
timezone: Asia/Kolkata
author: Ocean Mallik
email: hello@oceanmallik.com

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "assets/pages"
    values:
      layout: default

exclude:
  - README.md
  - .gitignore