name: Compress Images
on:
  push:
    paths:
      - 'assets/images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: '80'
          pngQuality: '80'
          webpQuality: '80'

      - name: Save Compressed Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-compressed images to save space"
